spring:
  application:
    name: cinemabackend

  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: jesscinemaapp@gmail.com
    password: tjiyvqkboxtgjlyo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  mail:
    from: jesscinemaapp@gmail.com
  auth:
    verification-expiration-hours: 24
    reset-expiration-minutes: 30
    session-expiration-hours: 8

card:
  encryption:
    key: ${CARD_ENCRYPTION_KEY:VGhpc0lzQVRlc3RLZXlGb3JBRVMxMjM0NTY3ODkwMTI=}
