services:
  postgres:
    image: postgres:16
    container_name: cinema-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

      # Runs only on first initialization
      - ./database/ddl.sql:/docker-entrypoint-initdb.d/01-ddl.sql
      - ./database/dml.sql:/docker-entrypoint-initdb.d/02-dml.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cinema"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest
    container_name: cinema-mailhog

    restart: unless-stopped

    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres-data:

